info:
  component: Config Server
spring:
  application:
    name: configserver
  jmx:
    default_domain: gensler.config.server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GenslerAppsPod/soa-Configurations.git
          username: ${sources.github.username:}
          password: ${sources.github.password:}
          repos:
            vision-services:
              uri: https://github.com/GenslerAppsPod/soa-Configurations.git
              username: ${sources.github.username:}
              password: ${sources.github.password:}
              cloneOnStart: true
              searchPaths: vi-configs

server:
  port: 8888
management:
  context_path: /admin
 